### ISSUE TITLE
Const pointers are handled improperly

### ISSUE THREAD

**Issue by marmistrz** [mozilla/moz-cheddar#6]
This code
```
extern crate libc;
use std::ffi::CStr;

#[no_mangle]
pub extern fn it_works(s: *const libc::c_char) {
    let cstr: &CStr = unsafe {
        assert!(!s.is_null());
        CStr::from_ptr(s)
    };
    println!("{}", cstr.to_string_lossy());
}
```
generates the following header
```
#ifndef cheddar_generated_crypto_pyrs_h
#define cheddar_generated_crypto_pyrs_h


#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>



void it_works(char const* s);



#ifdef __cplusplus
}
#endif


#endif
```
This declaration:
```
void it_works(char const* s);
```
is obviously incorrect.

**Comment by kinetiknz** [comment]
Can you explain how it's incorrect? It looks like `const` is correctly applied to the C declaration (i.e. it's a pointer to constant data).

**Comment by marmistrz** [comment]
It should be `char* const s`

**Comment by kinetiknz** [comment]
That would declare a constant pointer to a mutable char, which is not what `*const T` means in Rust:

> [have no guarantees about aliasing or mutability other than mutation not being allowed directly through a *const T.](https://doc.rust-lang.org/book/first-edition/raw-pointers.html)

..which semantically maps to `T const*` in C.

[See also](https://doc.rust-lang.org/book/first-edition/ffi.html) the declaration of `snappy_compress` in the FFI documentation, where the C function

    snappy_status snappy_compress(const char* input,
                                  size_t input_length,
                                  char* compressed,
                                  size_t* compressed_length);

is mapped to the Rust declaration

    fn snappy_compress(input: *const u8,
                       input_length: size_t,
                       compressed: *mut u8,
                       compressed_length: *mut size_t) -> c_int;

[bindgen (0.29.0)](https://github.com/rust-lang-nursery/rust-bindgen) also maps `void it_works(char const* s);` to `pub fn it_works(s: *const ::std::os::raw::c_char);`.

I'm going to close this as invalid.  Feel free to reopen it if you have a detailed explanation of why the current behaviour is incorrect.
